set vb t_vb=
set guifont=Monaco:h11
set guioptions-=rL

set guioptions-=T           " Remove the toolbar
"if !exists("g:spf13_no_big_font")
"  if LINUX() && has("gui_running")
"    set guifont=Andale\ Mono\ Regular\ 16,Menlo\ Regular\ 15,Consolas\ Regular\ 16,Courier\ New\ Regular\ 18
"  elseif OSX() && has("gui_running")
"    set guifont=Andale\ Mono\ Regular:h16,Menlo\ Regular:h15,Consolas\ Regular:h16,Courier\ New\ Regular:h18
"  elseif WINDOWS() && has("gui_running")
"    set guifont=Andale_Mono:h10,Menlo:h10,Consolas:h10,Courier_New:h10
"  endif
"endif
